// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one

INSERT INTO feed_follows (id, created_at, updated_at, user_id, feed_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, feed_id, user_id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

// Every query is scoped by user_id: a feed follow is only ever readable or
// deletable by the user it belongs to.
func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedID,
		&i.UserID,
	)
	return i, err
}

const deleteFeedFollowByIdAndUserId = `-- name: DeleteFeedFollowByIdAndUserId :exec
DELETE FROM feed_follows WHERE id = $1 AND user_id = $2
`

type DeleteFeedFollowByIdAndUserIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFeedFollowByIdAndUserId(ctx context.Context, arg DeleteFeedFollowByIdAndUserIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowByIdAndUserId, arg.ID, arg.UserID)
	return err
}

const deleteFeedFollowsByUserIdAndFeedId = `-- name: DeleteFeedFollowsByUserIdAndFeedId :exec
DELETE FROM feed_follows WHERE user_id = $1 AND feed_id = $2
`

type DeleteFeedFollowsByUserIdAndFeedIdParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeleteFeedFollowsByUserIdAndFeedId(ctx context.Context, arg DeleteFeedFollowsByUserIdAndFeedIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowsByUserIdAndFeedId, arg.UserID, arg.FeedID)
	return err
}

const getFeedFollowByIdAndUserId = `-- name: GetFeedFollowByIdAndUserId :one
SELECT id, created_at, updated_at, feed_id, user_id FROM feed_follows WHERE id = $1 AND user_id = $2
`

type GetFeedFollowByIdAndUserIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetFeedFollowByIdAndUserId(ctx context.Context, arg GetFeedFollowByIdAndUserIdParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, getFeedFollowByIdAndUserId, arg.ID, arg.UserID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedID,
		&i.UserID,
	)
	return i, err
}

const getFeedFollowsByUserIdAndFeedId = `-- name: GetFeedFollowsByUserIdAndFeedId :one
SELECT id, created_at, updated_at, feed_id, user_id FROM feed_follows WHERE user_id = $1 AND feed_id = $2
`

type GetFeedFollowsByUserIdAndFeedIdParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) GetFeedFollowsByUserIdAndFeedId(ctx context.Context, arg GetFeedFollowsByUserIdAndFeedIdParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, getFeedFollowsByUserIdAndFeedId, arg.UserID, arg.FeedID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedID,
		&i.UserID,
	)
	return i, err
}

const getFeedsFollowsByUserId = `-- name: GetFeedsFollowsByUserId :many
SELECT id, created_at, updated_at, feed_id, user_id FROM feed_follows WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetFeedsFollowsByUserId(ctx context.Context, userID uuid.UUID) ([]FeedFollow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsFollowsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollow
	for rows.Next() {
		var i FeedFollow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeedID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
