// Package database_test exercises the sqlc-generated queries against a real
// PostgreSQL instance. Everything here is skipped unless TEST_DATABASE_URL is
// set, so `go test ./...` stays runnable without a database.
package database_test

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"testing"
	"time"

	"rss-aggregator/internal/database"

	"github.com/google/uuid"
	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
)

var (
	testDB      *sql.DB
	testQueries *database.Queries
)

func TestMain(m *testing.M) {
	databaseURL := os.Getenv("TEST_DATABASE_URL")

	if databaseURL == "" {
		// No database configured: every test skips itself.
		os.Exit(m.Run())
	}

	db, err := sql.Open("pgx", databaseURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "cannot open the test database: %v\n", err)
		os.Exit(1)
	}

	if err := db.Ping(); err != nil {
		fmt.Fprintf(os.Stderr, "cannot reach the test database: %v\n", err)
		os.Exit(1)
	}

	// The tests run against the real schema, applied by the same migrations
	// that production uses.
	if err := goose.SetDialect("postgres"); err != nil {
		fmt.Fprintf(os.Stderr, "goose dialect: %v\n", err)
		os.Exit(1)
	}

	goose.SetLogger(goose.NopLogger())

	if err := goose.Up(db, "../../sql/schema"); err != nil {
		fmt.Fprintf(os.Stderr, "applying migrations: %v\n", err)
		os.Exit(1)
	}

	testDB = db
	testQueries = database.New(db)

	code := m.Run()

	db.Close()
	os.Exit(code)
}

// setup gives each test an empty database.
func setup(t *testing.T) (*database.Queries, context.Context) {
	t.Helper()

	if testQueries == nil {
		t.Skip("TEST_DATABASE_URL is not set")
	}

	if _, err := testDB.Exec("TRUNCATE items, channels, feed_follows, feeds, users RESTART IDENTITY CASCADE"); err != nil {
		t.Fatalf("truncating: %v", err)
	}

	return testQueries, context.Background()
}

func createUser(t *testing.T, queries *database.Queries, ctx context.Context, name string) database.User {
	t.Helper()

	user, err := queries.CreateUser(ctx, database.CreateUserParams{
		ID:        uuid.New(),
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		Fullname:  name,
	})

	if err != nil {
		t.Fatalf("creating user %q: %v", name, err)
	}

	return user
}

func createFeed(t *testing.T, queries *database.Queries, ctx context.Context, name, url string) database.Feed {
	t.Helper()

	feed, err := queries.CreateFeed(ctx, database.CreateFeedParams{
		ID:        uuid.New(),
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		Url:       url,
		Name:      name,
	})

	if err != nil {
		t.Fatalf("creating feed %q: %v", name, err)
	}

	return feed
}

func createChannel(t *testing.T, queries *database.Queries, ctx context.Context, feed database.Feed, title string) database.Channel {
	t.Helper()

	channel, err := queries.CreateChannel(ctx, database.CreateChannelParams{
		ID:        uuid.New(),
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		Title:     title,
		FeedID:    feed.ID,
	})

	if err != nil {
		t.Fatalf("creating channel %q: %v", title, err)
	}

	return channel
}

type itemFields struct {
	guid        string
	title       string
	category    string
	seeders     int32
	publishedAt time.Time
}

func createItem(t *testing.T, queries *database.Queries, ctx context.Context, channel database.Channel, fields itemFields) database.Item {
	t.Helper()

	item, err := queries.CreateItem(ctx, database.CreateItemParams{
		ID:          uuid.New(),
		Guid:        fields.guid,
		Title:       sql.NullString{String: fields.title, Valid: fields.title != ""},
		Category:    sql.NullString{String: fields.category, Valid: fields.category != ""},
		Seeders:     sql.NullInt32{Int32: fields.seeders, Valid: true},
		PublishedAt: sql.NullTime{Time: fields.publishedAt, Valid: !fields.publishedAt.IsZero()},
		CreatedAt:   time.Now().UTC(),
		UpdatedAt:   time.Now().UTC(),
		ChannelID:   channel.ID,
	})

	if err != nil {
		t.Fatalf("creating item %q: %v", fields.guid, err)
	}

	return item
}

func TestUserLifecycle(t *testing.T) {
	queries, ctx := setup(t)

	user := createUser(t, queries, ctx, "Matteo Campana")

	// The API key is generated by a column default, not by the application.
	if len(user.ApiKey) != 64 {
		t.Errorf("api key = %q, want 64 hex characters generated by the database", user.ApiKey)
	}

	found, err := queries.GetUserByApiKey(ctx, user.ApiKey)
	if err != nil {
		t.Fatalf("GetUserByApiKey: %v", err)
	}

	if found.ID != user.ID {
		t.Errorf("GetUserByApiKey returned %s, want %s", found.ID, user.ID)
	}

	if _, err := queries.GetUserByApiKey(ctx, "not-a-key"); !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("GetUserByApiKey with an unknown key = %v, want sql.ErrNoRows", err)
	}

	if err := queries.DeleteUser(ctx, user.ID); err != nil {
		t.Fatalf("DeleteUser: %v", err)
	}

	if _, err := queries.GetUser(ctx, user.ID); !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("GetUser after delete = %v, want sql.ErrNoRows", err)
	}
}

func TestUsersHaveDistinctApiKeys(t *testing.T) {
	queries, ctx := setup(t)

	first := createUser(t, queries, ctx, "First")
	second := createUser(t, queries, ctx, "Second")

	if first.ApiKey == second.ApiKey {
		t.Error("two users share an API key: the default must generate a new one per row")
	}
}

// The scraper picks the feeds it has not seen in the longest time, and a feed
// that was never fetched has to come first.
func TestGetNextFeedsToFetchPutsNeverFetchedFirst(t *testing.T) {
	queries, ctx := setup(t)

	fetched := createFeed(t, queries, ctx, "already fetched", "https://example.com/a.xml")
	never := createFeed(t, queries, ctx, "never fetched", "https://example.com/b.xml")

	if _, err := queries.MarkFeedAsFetched(ctx, fetched.ID); err != nil {
		t.Fatalf("MarkFeedAsFetched: %v", err)
	}

	feeds, err := queries.GetNextFeedsToFetch(ctx, 10)
	if err != nil {
		t.Fatalf("GetNextFeedsToFetch: %v", err)
	}

	if len(feeds) != 2 {
		t.Fatalf("got %d feeds, want 2", len(feeds))
	}

	if feeds[0].ID != never.ID {
		t.Errorf("first feed = %q, want the never fetched one", feeds[0].Name)
	}

	if !feeds[1].LastFetchedAt.Valid {
		t.Error("MarkFeedAsFetched left last_fetched_at NULL")
	}
}

func TestGetNextFeedsToFetchHonoursTheLimit(t *testing.T) {
	queries, ctx := setup(t)

	for i := 0; i < 5; i++ {
		createFeed(t, queries, ctx, fmt.Sprintf("feed %d", i), fmt.Sprintf("https://example.com/%d.xml", i))
	}

	feeds, err := queries.GetNextFeedsToFetch(ctx, 2)
	if err != nil {
		t.Fatalf("GetNextFeedsToFetch: %v", err)
	}

	if len(feeds) != 2 {
		t.Errorf("got %d feeds, want the limit of 2", len(feeds))
	}
}

// The regression this locks in: a GUID is unique per channel, not globally, so
// two feeds carrying the same torrent each keep their own row.
func TestSameGuidCanExistInTwoChannels(t *testing.T) {
	queries, ctx := setup(t)

	feedA := createFeed(t, queries, ctx, "feed A", "https://example.com/a.xml")
	feedB := createFeed(t, queries, ctx, "feed B", "https://example.com/b.xml")

	channelA := createChannel(t, queries, ctx, feedA, "channel A")
	channelB := createChannel(t, queries, ctx, feedB, "channel B")

	const guid = "https://nyaa.si/view/1800001"

	createItem(t, queries, ctx, channelA, itemFields{guid: guid, title: "in A", seeders: 10})
	createItem(t, queries, ctx, channelB, itemFields{guid: guid, title: "in B", seeders: 20})

	inA, err := queries.GetItemByChannelIdAndGuid(ctx, database.GetItemByChannelIdAndGuidParams{
		ChannelID: channelA.ID,
		Guid:      guid,
	})

	if err != nil {
		t.Fatalf("looking the item up in channel A: %v", err)
	}

	inB, err := queries.GetItemByChannelIdAndGuid(ctx, database.GetItemByChannelIdAndGuidParams{
		ChannelID: channelB.ID,
		Guid:      guid,
	})

	if err != nil {
		t.Fatalf("looking the item up in channel B: %v", err)
	}

	if inA.ID == inB.ID {
		t.Fatal("both channels resolve to the same row: the GUID is still globally unique")
	}

	if inA.Title.String != "in A" || inB.Title.String != "in B" {
		t.Errorf("rows got mixed up: %q / %q", inA.Title.String, inB.Title.String)
	}
}

func TestTheSameGuidTwiceInOneChannelIsRejected(t *testing.T) {
	queries, ctx := setup(t)

	feed := createFeed(t, queries, ctx, "feed", "https://example.com/a.xml")
	channel := createChannel(t, queries, ctx, feed, "channel")

	createItem(t, queries, ctx, channel, itemFields{guid: "duplicate", title: "first"})

	_, err := queries.CreateItem(ctx, database.CreateItemParams{
		ID:        uuid.New(),
		Guid:      "duplicate",
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		ChannelID: channel.ID,
	})

	if err == nil {
		t.Fatal("inserting the same GUID twice in one channel succeeded, want a unique violation")
	}
}

func TestUpdateItemKeepsTheRow(t *testing.T) {
	queries, ctx := setup(t)

	feed := createFeed(t, queries, ctx, "feed", "https://example.com/a.xml")
	channel := createChannel(t, queries, ctx, feed, "channel")
	item := createItem(t, queries, ctx, channel, itemFields{guid: "g1", title: "before", seeders: 1})

	updated, err := queries.UpdateItem(ctx, database.UpdateItemParams{
		ID:        item.ID,
		Guid:      "g1",
		Title:     sql.NullString{String: "after", Valid: true},
		Seeders:   sql.NullInt32{Int32: 99, Valid: true},
		UpdatedAt: time.Now().UTC(),
		ChannelID: channel.ID,
	})

	if err != nil {
		t.Fatalf("UpdateItem: %v", err)
	}

	if updated.ID != item.ID {
		t.Errorf("UpdateItem created a new row: %s vs %s", updated.ID, item.ID)
	}

	if updated.Seeders.Int32 != 99 || updated.Title.String != "after" {
		t.Errorf("row not updated: seeders=%d title=%q", updated.Seeders.Int32, updated.Title.String)
	}
}

// listItems fills a channel with a known set of items, so the filters can be
// checked against a fixed expectation.
func seedItems(t *testing.T, queries *database.Queries, ctx context.Context) database.Channel {
	t.Helper()

	feed := createFeed(t, queries, ctx, "feed", "https://example.com/a.xml")
	channel := createChannel(t, queries, ctx, feed, "channel")

	base := time.Date(2024, 6, 25, 10, 0, 0, 0, time.UTC)

	createItem(t, queries, ctx, channel, itemFields{
		guid: "g1", title: "[SubsPlease] Alpha", category: "Anime", seeders: 1000, publishedAt: base,
	})
	createItem(t, queries, ctx, channel, itemFields{
		guid: "g2", title: "[Erai-raws] Beta", category: "Anime", seeders: 50, publishedAt: base.Add(-time.Hour),
	})
	createItem(t, queries, ctx, channel, itemFields{
		guid: "g3", title: "[Other] Gamma", category: "Live Action", seeders: 500, publishedAt: base.Add(-2 * time.Hour),
	})

	return channel
}

func listItems(t *testing.T, queries *database.Queries, ctx context.Context, params database.ListItemsParams) []database.ListItemsRow {
	t.Helper()

	if params.Sort == "" {
		params.Sort = "recent"
	}

	if params.PageSize == 0 {
		params.PageSize = 50
	}

	rows, err := queries.ListItems(ctx, params)
	if err != nil {
		t.Fatalf("ListItems: %v", err)
	}

	return rows
}

func TestListItemsFilters(t *testing.T) {
	queries, ctx := setup(t)
	channel := seedItems(t, queries, ctx)

	tests := []struct {
		name   string
		params database.ListItemsParams
		want   []string
	}{
		{
			name:   "no filter",
			params: database.ListItemsParams{},
			want:   []string{"g1", "g2", "g3"},
		},
		{
			name:   "search is case insensitive and partial",
			params: database.ListItemsParams{Search: sql.NullString{String: "erai", Valid: true}},
			want:   []string{"g2"},
		},
		{
			name:   "category",
			params: database.ListItemsParams{Category: sql.NullString{String: "Live Action", Valid: true}},
			want:   []string{"g3"},
		},
		{
			name:   "min seeders",
			params: database.ListItemsParams{MinSeeders: sql.NullInt32{Int32: 500, Valid: true}},
			want:   []string{"g1", "g3"},
		},
		{
			name:   "channel",
			params: database.ListItemsParams{ChannelID: uuid.NullUUID{UUID: channel.ID, Valid: true}},
			want:   []string{"g1", "g2", "g3"},
		},
		{
			name:   "another channel matches nothing",
			params: database.ListItemsParams{ChannelID: uuid.NullUUID{UUID: uuid.New(), Valid: true}},
			want:   []string{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rows := listItems(t, queries, ctx, tt.params)

			got := make([]string, 0, len(rows))
			for _, row := range rows {
				got = append(got, row.Guid)
			}

			if len(got) != len(tt.want) {
				t.Fatalf("got %v, want %v", got, tt.want)
			}

			seen := map[string]bool{}
			for _, guid := range got {
				seen[guid] = true
			}

			for _, guid := range tt.want {
				if !seen[guid] {
					t.Errorf("got %v, want it to contain %q", got, guid)
				}
			}
		})
	}
}

func TestListItemsSorting(t *testing.T) {
	queries, ctx := setup(t)
	seedItems(t, queries, ctx)

	tests := []struct {
		sort  string
		first string
	}{
		{sort: "recent", first: "g1"},
		{sort: "oldest", first: "g3"},
		{sort: "seeders", first: "g1"},
	}

	for _, tt := range tests {
		t.Run(tt.sort, func(t *testing.T) {
			rows := listItems(t, queries, ctx, database.ListItemsParams{Sort: tt.sort})

			if len(rows) == 0 {
				t.Fatal("no rows")
			}

			if rows[0].Guid != tt.first {
				t.Errorf("first row = %q, want %q", rows[0].Guid, tt.first)
			}
		})
	}
}

// The total has to describe the filtered set, not the table, or the frontend
// paginates over a count that does not match what it shows.
func TestListItemsTotalFollowsTheFilters(t *testing.T) {
	queries, ctx := setup(t)
	seedItems(t, queries, ctx)

	rows := listItems(t, queries, ctx, database.ListItemsParams{PageSize: 1})

	if len(rows) != 1 {
		t.Fatalf("got %d rows, want the page size of 1", len(rows))
	}

	if rows[0].TotalCount != 3 {
		t.Errorf("total = %d, want 3", rows[0].TotalCount)
	}

	filtered := listItems(t, queries, ctx, database.ListItemsParams{
		MinSeeders: sql.NullInt32{Int32: 500, Valid: true},
		PageSize:   1,
	})

	if filtered[0].TotalCount != 2 {
		t.Errorf("filtered total = %d, want 2", filtered[0].TotalCount)
	}
}

func TestListItemsPaginationWalksEveryRowOnce(t *testing.T) {
	queries, ctx := setup(t)
	seedItems(t, queries, ctx)

	seen := map[string]bool{}

	for page := 0; page < 3; page++ {
		rows := listItems(t, queries, ctx, database.ListItemsParams{
			Sort:       "seeders",
			PageSize:   1,
			PageOffset: int32(page),
		})

		if len(rows) != 1 {
			t.Fatalf("page %d returned %d rows, want 1", page, len(rows))
		}

		if seen[rows[0].Guid] {
			t.Errorf("page %d repeated %q", page, rows[0].Guid)
		}

		seen[rows[0].Guid] = true
	}

	if len(seen) != 3 {
		t.Errorf("saw %d distinct items over three pages, want 3", len(seen))
	}
}

func TestListItemCategoriesIsDistinctAndSorted(t *testing.T) {
	queries, ctx := setup(t)
	seedItems(t, queries, ctx)

	categories, err := queries.ListItemCategories(ctx)
	if err != nil {
		t.Fatalf("ListItemCategories: %v", err)
	}

	if len(categories) != 2 {
		t.Fatalf("got %d categories, want 2 distinct ones", len(categories))
	}

	if categories[0].String != "Anime" || categories[1].String != "Live Action" {
		t.Errorf("categories = %q/%q, want them sorted", categories[0].String, categories[1].String)
	}
}

// The security regression: every feed-follow query is scoped by user_id, so one
// user's key can never reach another user's rows.
func TestFeedFollowsAreScopedToTheirUser(t *testing.T) {
	queries, ctx := setup(t)

	alice := createUser(t, queries, ctx, "Alice")
	bob := createUser(t, queries, ctx, "Bob")
	feed := createFeed(t, queries, ctx, "feed", "https://example.com/a.xml")

	follow, err := queries.CreateFeedFollow(ctx, database.CreateFeedFollowParams{
		ID:        uuid.New(),
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		UserID:    bob.ID,
		FeedID:    feed.ID,
	})

	if err != nil {
		t.Fatalf("CreateFeedFollow: %v", err)
	}

	if _, err := queries.GetFeedFollowByIdAndUserId(ctx, database.GetFeedFollowByIdAndUserIdParams{
		ID:     follow.ID,
		UserID: alice.ID,
	}); !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("Alice reading Bob's follow = %v, want sql.ErrNoRows", err)
	}

	if _, err := queries.GetFeedFollowsByUserIdAndFeedId(ctx, database.GetFeedFollowsByUserIdAndFeedIdParams{
		UserID: alice.ID,
		FeedID: feed.ID,
	}); !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("Alice reading Bob's follow by feed = %v, want sql.ErrNoRows", err)
	}

	aliceFollows, err := queries.GetFeedsFollowsByUserId(ctx, alice.ID)
	if err != nil {
		t.Fatalf("GetFeedsFollowsByUserId: %v", err)
	}

	if len(aliceFollows) != 0 {
		t.Errorf("Alice sees %d follows, want none of Bob's", len(aliceFollows))
	}

	// A delete aimed at somebody else's row must not remove it.
	if err := queries.DeleteFeedFollowByIdAndUserId(ctx, database.DeleteFeedFollowByIdAndUserIdParams{
		ID:     follow.ID,
		UserID: alice.ID,
	}); err != nil {
		t.Fatalf("DeleteFeedFollowByIdAndUserId: %v", err)
	}

	if _, err := queries.GetFeedFollowByIdAndUserId(ctx, database.GetFeedFollowByIdAndUserIdParams{
		ID:     follow.ID,
		UserID: bob.ID,
	}); err != nil {
		t.Errorf("Bob's follow disappeared after Alice's delete: %v", err)
	}

	// Bob deleting his own does work.
	if err := queries.DeleteFeedFollowByIdAndUserId(ctx, database.DeleteFeedFollowByIdAndUserIdParams{
		ID:     follow.ID,
		UserID: bob.ID,
	}); err != nil {
		t.Fatalf("Bob deleting his own follow: %v", err)
	}

	if _, err := queries.GetFeedFollowByIdAndUserId(ctx, database.GetFeedFollowByIdAndUserIdParams{
		ID:     follow.ID,
		UserID: bob.ID,
	}); !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("follow still there after Bob deleted it = %v, want sql.ErrNoRows", err)
	}
}

func TestListFeedsPagination(t *testing.T) {
	queries, ctx := setup(t)

	for i := 0; i < 3; i++ {
		createFeed(t, queries, ctx, fmt.Sprintf("feed %d", i), fmt.Sprintf("https://example.com/%d.xml", i))
	}

	rows, err := queries.ListFeeds(ctx, database.ListFeedsParams{PageSize: 2, PageOffset: 0})
	if err != nil {
		t.Fatalf("ListFeeds: %v", err)
	}

	if len(rows) != 2 {
		t.Fatalf("got %d rows, want the page size of 2", len(rows))
	}

	if rows[0].TotalCount != 3 {
		t.Errorf("total = %d, want 3", rows[0].TotalCount)
	}

	second, err := queries.ListFeeds(ctx, database.ListFeedsParams{PageSize: 2, PageOffset: 2})
	if err != nil {
		t.Fatalf("ListFeeds page 2: %v", err)
	}

	if len(second) != 1 {
		t.Errorf("second page has %d rows, want 1", len(second))
	}
}

func TestListUsersPagination(t *testing.T) {
	queries, ctx := setup(t)

	for i := 0; i < 3; i++ {
		createUser(t, queries, ctx, fmt.Sprintf("user %d", i))
	}

	rows, err := queries.ListUsers(ctx, database.ListUsersParams{PageSize: 2, PageOffset: 0})
	if err != nil {
		t.Fatalf("ListUsers: %v", err)
	}

	if len(rows) != 2 {
		t.Fatalf("got %d rows, want 2", len(rows))
	}

	if rows[0].TotalCount != 3 {
		t.Errorf("total = %d, want 3", rows[0].TotalCount)
	}
}

func TestChannelsAreFoundByTitle(t *testing.T) {
	queries, ctx := setup(t)

	feed := createFeed(t, queries, ctx, "feed", "https://example.com/a.xml")
	channel := createChannel(t, queries, ctx, feed, "Nyaa - Home")

	found, err := queries.GetChannelByTitle(ctx, "Nyaa - Home")
	if err != nil {
		t.Fatalf("GetChannelByTitle: %v", err)
	}

	if found.ID != channel.ID {
		t.Errorf("got %s, want %s", found.ID, channel.ID)
	}

	if _, err := queries.GetChannelByTitle(ctx, "missing"); !errors.Is(err, sql.ErrNoRows) {
		t.Errorf("unknown title = %v, want sql.ErrNoRows", err)
	}
}
