// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Channel struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description sql.NullString
	Link        sql.NullString
	AtomLink    sql.NullString
	FeedID      uuid.UUID
}

type Feed struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Url       string
	Name      string
}

type FeedFollow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FeedID    uuid.UUID
	UserID    uuid.UUID
}

type Item struct {
	ID          uuid.UUID
	Title       sql.NullString
	Link        sql.NullString
	Guid        string
	Pubdate     sql.NullString
	Seeders     sql.NullInt32
	Leechers    sql.NullInt32
	Downloads   sql.NullInt32
	Infohash    sql.NullString
	CategoryID  sql.NullString
	Category    sql.NullString
	Size        sql.NullString
	Comments    sql.NullInt32
	Trusted     sql.NullString
	Remake      sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ChannelID   uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Fullname  string
	Firstname sql.NullString
	Lastname  sql.NullString
	Email     sql.NullString
}
