-- +goose Up

CREATE TABLE feeds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    url TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE
);

-- +goose Down

DROP TABLE IF EXISTS feeds;